"""Pack static captions without duplicating the complete single-glyph atlas."""
import argparse
import ast
import json
import math
from pathlib import Path
import re
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
PAGE = 2048


def build(font_path):
    app = ROOT / 'behavior_pack/HelloScript/projection'
    dest = ROOT / 'resource_pack/textures/modern_projection/type'
    font = ImageFont.truetype(str(font_path), 64)
    font.set_variation_by_name('Medium')
    phrases = set()
    for path in app.glob('*.py'):
        if path.name in ('type_assets.py', 'font_atlas.py'):
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding='utf8'))):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                value = node.value
                if 1 < len(value) < 150 and '\n' not in value and any(ord(c) > 127 for c in value):
                    phrases.add(value)
    metrics = [(value, font.getlength(value)) for value in sorted(phrases)]
    # Long captions already use the wrapping single-glyph renderer. Keep every
    # page <= 2048 pixels, matching the existing mobile-compatible glyph atlas.
    metrics = [(value, advance, math.ceil(advance)+4) for value, advance in metrics
               if math.ceil(advance)+4 <= PAGE-4]
    metrics.sort(key=lambda item: (-item[2], item[0]))
    result = {}; pages = []; page = 0; x = y = 2
    image = Image.new('RGBA', (PAGE, PAGE), (255,255,255,0))
    draw = ImageDraw.Draw(image)
    dest.mkdir(parents=True, exist_ok=True)
    def save():
        name = 'phrases_%03d.png' % page
        image.save(dest/name, optimize=True)
        pages.append(name)
    for value, advance, width in metrics:
        if x+width+2 > PAGE:
            x, y = 2, y+92
        if y+90 > PAGE:
            save(); page += 1; x = y = 2
            image = Image.new('RGBA', (PAGE, PAGE), (255,255,255,0))
            draw = ImageDraw.Draw(image)
        draw.text((x+1,y+69), value, font=font, fill='white', anchor='ls')
        result[value] = ['phrases_%03d'%page, width/64., 88/64., advance/64., [x,y], [width,88]]
        x += width+4
    save()
    (app/'type_assets.py').write_text(
        '# -*- coding: utf-8 -*-\n# Generated by tools/generate_phrase_atlas.py; Noto Sans SC (OFL).\n'
        'import json\nASSETS = json.loads(r\'\'\''+json.dumps(result,ensure_ascii=True,separators=(',',':'))+"''')\n", encoding='utf8')
    # Only obsolete generated text images in this exact directory are removed.
    # Complete glyph pages, other textures and font licence are preserved.
    directory = dest.resolve()
    removed = []; removed_bytes = 0
    for path in dest.glob('*.png'):
        if re.fullmatch(r'[0-9a-f]{16}', path.stem) or (path.stem.startswith('phrases_') and path.name not in pages):
            assert path.resolve().parent == directory
            removed_bytes += path.stat().st_size
            removed.append(path.name)
            path.unlink()
    print('Packed %d captions into %d pages (%d bytes); removed %d old images (%d bytes)' % (
        len(result),len(pages),sum((dest/name).stat().st_size for name in pages),len(removed),removed_bytes))


if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--font',required=True)
    build(parser.parse_args().font)
