"""Rebuild local smooth typography, icons and native JsonUI skins with Pillow."""
import argparse
import ast
import hashlib
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / 'behavior_pack/HelloScript/projection'
OUT = ROOT / 'resource_pack/textures/modern_projection'


def sprites(font_path):
    font = ImageFont.truetype(str(font_path), 64)
    if hasattr(font, 'set_variation_by_name'):
        font.set_variation_by_name('Medium')
    phrases = set()
    for path in APP.glob('*.py'):
        if path.name == 'type_assets.py':
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding='utf8'))):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                value = node.value
                if 0 < len(value) < 150 and '\n' not in value and any(ord(c) > 127 for c in value):
                    phrases.add(value)
    chars = set(''.join(phrases)) | set(chr(i) for i in range(32, 127))
    result = {}
    dest = OUT / 'type'
    dest.mkdir(parents=True, exist_ok=True)
    for value in sorted(phrases | chars):
        advance = font.getlength(value)
        width = max(1, math.ceil(advance) + 4)
        bitmap = Image.new('RGBA', (width, 88))
        ImageDraw.Draw(bitmap).text((1, 69), value, font=font, fill='white', anchor='ls')
        name = hashlib.sha256(value.encode('utf8')).hexdigest()[:16]
        bitmap.save(dest / (name + '.png'), optimize=True)
        result[value] = [name, width / 64., 88 / 64., advance / 64.]
    (APP / 'type_assets.py').write_text(
        '# -*- coding: utf-8 -*-\n# Generated by tools/generate_assets.py; Noto Sans SC (OFL).\n'
        'import json\nASSETS = json.loads(r\'\'\'' + json.dumps(result, ensure_ascii=True) + '\'\'\')\n', encoding='utf8')
    print('Generated %d smooth text sprites' % len(result))


def shape(name, size, draw):
    img = Image.new('RGBA', (size[0] * 3, size[1] * 3))
    draw(ImageDraw.Draw(img), 3)
    img.resize(size, Image.Resampling.LANCZOS).save(OUT / (name + '.png'))


def graphics():
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / 'icons').mkdir(exist_ok=True)
    shape('rounded', (64, 64), lambda d, s: d.rounded_rectangle((0, 0, 64*s-1, 64*s-1), 24*s, fill='white'))
    shape('dot', (16, 16), lambda d, s: d.ellipse((1*s, 1*s, 15*s, 15*s), fill='white'))
    shape('knob', (36, 36), lambda d, s: (d.ellipse((2*s, 3*s, 34*s, 35*s), fill='#CCD8EE'),
        d.ellipse((3*s, 2*s, 33*s, 32*s), fill='white'), d.ellipse((13*s, 12*s, 23*s, 22*s), fill='#477AF4')))
    Image.new('RGBA', (2, 2)).save(OUT / 'transparent.png')
    for name, color in [('input_bg', '#F0F4FA'), ('input_hover', '#E6EDFA')]:
        shape(name, (32, 32), lambda d, s, c=color: d.rounded_rectangle((0, 0, 32*s-1, 32*s-1), 6*s, fill=c))
    grid = Image.new('RGBA', (800, 800), '#F7F9FC')
    d = ImageDraw.Draw(grid)
    for x in range(0, 800, 24):
        for y in range(0, 800, 24):
            d.ellipse((x, y, x+1, y+1), fill='#C7D3E2')
    grid.save(OUT / 'viewport_grid.png')
    paths = {
        'plus': [[(12,4),(12,20)],[(4,12),(20,12)]],
        'minus': [[(4,12),(20,12)]],
        'close': [[(6,6),(18,18)],[(18,6),(6,18)]],
        'cube': [[(12,2),(22,7),(22,17),(12,22),(2,17),(2,7),(12,2)],[(2,7),(12,12),(22,7)],[(12,12),(12,22)]],
        'cursor': [[(4,2),(4,20),(9,15),(13,22),(17,20),(13,13),(21,13),(4,2)]],
        'brush': [[(6,15),(16,3),(21,8),(10,19),(6,15)],[(6,15),(3,17),(3,22),(8,21),(10,19)]],
        'move': [[(12,2),(12,22)],[(2,12),(22,12)],[(8,6),(12,2),(16,6)],[(8,18),(12,22),(16,18)],[(6,8),(2,12),(6,16)],[(18,8),(22,12),(18,16)]],
        'grid': [[(3,3),(21,3),(21,21),(3,21),(3,3)],[(9,3),(9,21)],[(15,3),(15,21)],[(3,9),(21,9)],[(3,15),(21,15)]],
        'spark': [[(12,2),(15,9),(22,12),(15,15),(12,22),(9,15),(2,12),(9,9),(12,2)]],
        'save': [[(3,3),(17,3),(21,7),(21,21),(3,21),(3,3)],[(7,3),(7,9),(16,9),(16,3)],[(7,21),(7,14),(17,14),(17,21)]],
        'undo': [[(7,4),(3,8),(7,12)],[(3,8),(14,8),(19,11),(20,15),(18,19),(13,20)]],
        'redo': [[(17,4),(21,8),(17,12)],[(21,8),(10,8),(5,11),(4,15),(6,19),(11,20)]],
        'eye': [[(2,12),(6,7),(12,5),(18,7),(22,12),(18,17),(12,19),(6,17),(2,12)],[(12,9),(15,12),(12,15),(9,12),(12,9)]],
        'lock': [[(5,10),(19,10),(19,21),(5,21),(5,10)],[(8,10),(8,6),(10,3),(14,3),(16,6),(16,10)],[(12,14),(12,17)]],
        'unlock': [[(5,10),(19,10),(19,21),(5,21),(5,10)],[(8,10),(8,6),(10,3),(15,3),(18,6)],[(12,14),(12,17)]],
        'home': [[(2,11),(12,2),(22,11)],[(5,9),(5,22),(10,22),(10,15),(15,15),(15,22),(19,22),(19,9)]],
        'orbit': [[(4,8),(7,4),(12,2),(18,4),(21,9),(21,15),(18,20),(11,22),(5,19),(3,14)],[(3,4),(4,8),(9,8)],[(6,12),(12,16),(19,12)]],
        'play': [[(7,3),(21,12),(7,21),(7,3)]],
        'pin': [[(12,22),(5,13),(4,8),(7,3),(12,2),(18,4),(20,9),(18,14),(12,22)],[(12,7),(15,10),(12,13),(9,10),(12,7)]],
        'library': [[(3,3),(8,3),(8,21),(3,21),(3,3)],[(11,3),(16,3),(16,21),(11,21),(11,3)],[(18,4),(23,20)]],
        'projection': [[(12,2),(21,7),(21,16),(12,21),(3,16),(3,7),(12,2)],[(3,7),(12,12),(21,7)],[(12,12),(12,21)],[(1,22),(23,22)]],
        'check': [[(3,12),(9,18),(21,5)]],
        'info': [[(12,9),(12,17)],[(12,5),(12,6)],[(12,2),(19,5),(22,12),(19,19),(12,22),(5,19),(2,12),(5,5),(12,2)]],
    }
    for name, strokes in paths.items():
        img = Image.new('RGBA', (96,96))
        d = ImageDraw.Draw(img)
        for stroke in strokes:
            d.line([(x*4,y*4) for x,y in stroke], fill='white', width=7, joint='curve')
        img.resize((48,48),Image.Resampling.LANCZOS).save(OUT / 'icons' / (name+'.png'))
    logo = Image.new('RGBA', (128,128))
    d = ImageDraw.Draw(logo)
    d.rounded_rectangle((0,0,127,127),32,fill='#477AF4')
    d.polygon([(64,24),(103,45),(103,84),(64,105),(25,84),(25,45)], fill='#DDE8FF')
    d.polygon([(64,66),(103,45),(103,84),(64,105)], fill='#92B3FF')
    d.line([(25,45),(64,66),(103,45)],fill='white',width=3)
    d.line([(64,66),(64,105)],fill='white',width=3)
    logo.save(OUT/'logo.png')
    axes=Image.new('RGBA',(150,150)); d=ImageDraw.Draw(axes)
    for end,color in [((125,105),'#EF8690'),((28,108),'#6E9AF1'),((76,22),'#60B9A0')]:
        d.line([(76,78),end],fill=color,width=4); x,y=end; d.ellipse((x-7,y-7,x+7,y+7),fill=color)
    d.ellipse((70,72,82,84),fill='#8394AC'); axes.save(OUT/'axes.png')


def native_skin():
    # Based on the documented common slider structure; our visual track is Pyreact.
    ns='ModernProjection'; tex='textures/modern_projection/'
    skin={'namespace':ns,
        'label@PyreactBase.label':{'font_type':'smooth','backup_font_type':'smooth'},
        'type_image@PyreactBase.image':{'bilinear':True},
        'doll@PyreactBase.paperDoll':{'rotation':'freedom_gesture'},
        'input_background':{'type':'image','texture':tex+'input_bg','size':['100%','100%'],'keep_ratio':False,'nineslice_size':[4,4,4,4],'bilinear':True},
        'input_hover@ModernProjection.input_background':{'texture':tex+'input_hover'},
        'input@PyreactBase.input':{'$text_background_default':ns+'.input_background', '$text_background_hover':ns+'.input_hover',
            '$edit_box_default_texture':tex+'input_bg', '$edit_box_hover_texture':tex+'input_hover', '$font_scale_factor':.8,
            '$place_holder_text':'', '$text_box_text_color':[.15,.22,.30]},
        'invisible':{'type':'image','texture':tex+'transparent','size':['100%','100%'],'alpha':0},
        'scroll_thumb':{'type':'image','texture':'textures/ui/white','size':[2,'100%'],
                        'color':[.65,.73,.85],'layer':4},
        'scroll@PyreactBase.scrollBase':{'$scroll_size':[3,'100%'],'$scroll_track_image_control':'common.empty_panel',
            '$scroll_box_mouse_image_control':ns+'.scroll_thumb','$scroll_box_touch_image_control':ns+'.scroll_thumb'},
    }
    slider={'$slider_box_size':[4,10]}
    for state in ('default','hover'):
        for kind in ('background','progress'):
            slider['$%s_%s_control'%(kind,state)]=ns+'.invisible'
    for state in ('','_hover','_locked','_indent'):
        slider['$slider_box%s_layout'%state]='common.empty_panel'
    for state in ('default','hover'):
        names=['slider_background','slider_progress'] if state=='default' else ['slider_background_hover','slider_progress_hover']
        skin['slider_bar_'+state]={'type':'image','texture':tex+'transparent','controls':[{'sizing_panel':{
            'type':'panel','controls':[{n+'@ModernProjection.invisible':{}} for n in names]}}]}
    slider['controls']=[{'slider_box@common.slider_box':{'$slider_box_layout':'$slider_box_layout',
        '$slider_box_size':'$slider_box_size','$slider_track_button':'$slider_name'}},
        {'slider_bar_default@ModernProjection.slider_bar_default':{}},
        {'slider_bar_hover@ModernProjection.slider_bar_hover':{'visible':False}}]
    skin['slider@PyreactBase.slider']=slider
    path=ROOT/'resource_pack/ui/ModernProjection.json'
    path.write_text(json.dumps(skin,ensure_ascii=False,indent=2),encoding='utf8')
    base_path=ROOT/'resource_pack/ui/PyreactBase.json'
    base=json.loads(base_path.read_text(encoding='utf8'))
    controls=base['rootBase']['controls']
    for suffix,target in [('label','label'),('type','type_image'),('input','input'),('slider','slider'),('doll','doll'),('scroll','scroll')]:
        key='mp_%s_tmpl@ModernProjection.%s'%(suffix,target)
        if not any(key in c for c in controls):
            controls.append({key:{}})
    base_path.write_text(json.dumps(base,ensure_ascii=False,indent=2),encoding='utf8')
    defs=ROOT/'resource_pack/ui/_ui_defs.json'
    data=json.loads(defs.read_text(encoding='utf8'))
    if 'ui/ModernProjection.json' not in data['ui_defs']:
        data['ui_defs'].append('ui/ModernProjection.json')
    defs.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf8')


if __name__=='__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--font',required=True); args=parser.parse_args()
    sprites(args.font); graphics(); native_skin()
