"""Generate the portable, lazy block registry from a native block_palette.json."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import zlib

ROOT = Path(__file__).resolve().parents[1]


def generate(source):
    raw = source.read_bytes()
    records = json.loads(raw)['blocks']
    blocks = {}
    for row in records:
        name, aux = row['name'], row['data']
        states = sorted((s['name'],s['type'],s['value']) for s in row['states'])
        assert all(t in ('byte','int','string') for k,t,v in states)
        assert aux not in blocks.setdefault(name, {})
        blocks[name][aux] = states
    aliases = json.loads((ROOT/'tools/data/legacy_block_aliases.json').read_text(encoding='utf8'))
    compatible = {}
    for name,aux,target,data in aliases['rows']:
        if aux in blocks.get(name, {}):
            continue  # A real modern state always wins over item/drop aliases.
        assert data in blocks[target]
        compatible.setdefault(name, {})[aux] = (target,data)
    def pack(value):
        return base64.b64encode(zlib.compress(json.dumps(value,separators=(',',':')).encode('ascii'),9)).decode('ascii')
    lines = ['# Generated by tools/generate_block_registry.py; do not edit.',
             'from __future__ import unicode_literals',
             'SOURCE_SHA256 = '+repr(hashlib.sha256(raw).hexdigest()),
             'RECORD_COUNT = '+str(len(records)), 'BLOCKS = {']
    for name,rows in sorted(blocks.items()):
        lines.append('    '+repr(name)+': '+repr(pack(sorted(rows.items())))+',')
    lines.extend(['}', 'DEFAULT_AUX = {'])
    for name,rows in sorted(blocks.items()):
        lines.append('    '+repr(name)+': '+str(min(rows))+',')
    lines.extend(['}', 'ALIASES = {'])
    for name,rows in sorted(compatible.items()):
        lines.append('    '+repr(name)+': '+repr(pack(sorted(rows.items())))+',')
    lines.extend(['}', ''])
    path = ROOT/'behavior_pack/modern_projection/projection/block_registry_data.py'
    path.write_text('\n'.join(lines),encoding='ascii')
    print('%d names, %d states, %d legacy aliases; %d bytes' % (
        len(blocks),len(records),sum(len(v) for v in compatible.values()),path.stat().st_size))


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source',type=Path)
    generate(parser.parse_args().source)
